name: markr
description: A test ingestion & processing service.
version: 1.0.0
repository: https://github.com/Adroz/markr

environment:
  sdk: ^3.3.4

dependencies:
  args: ^2.4.0
  collection: ^1.18.0
  objectbox: ^2.5.1
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  xml: ^6.5.0

dev_dependencies:
  build_runner: ^2.4.9
  http: ^1.1.0
  lints: ^3.0.0
  objectbox_generator: any
  test: ^1.24.0
