name: markr
description: A test ingestion & processing service.
version: 1.0.0
repository: https://github.com/Adroz/markr

environment:
  sdk: ^3.3.4

dependencies:
  args: ^2.4.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0

dev_dependencies:
  http: ^1.1.0
  lints: ^3.0.0
  test: ^1.24.0
